# Build with
# cargo about generate about.hbs > docs/_static/opensource_licenses2.html
accepted = [
    "Apache-2.0",
    "MIT",
    "BSD-3-Clause",
    "Apache-2.0 WITH LLVM-exception",
    "Unicode-DFS-2016"
]

private = { ignore = true }

ignore-build-dependencies = true
ignore-dev-dependencies = true

[parking_lot_core.clarify]
license = "MIT"

[[parking_lot_core.clarify.files]]
path = 'LICENSE-MIT'
license = 'MIT'
checksum = 'c9a75f18b9ab2927829a208fc6aa2cf4e63b8420887ba29cdb265d6619ae82d5'
